Repository redhat-partner-solutions/rhel-sriov-test, pull requests merged in 2022-07, with the labels that each got.

#17 Adding logging of commands to SR_IOV_MultipleVFCreation_withMTU
  sriov/tests/SR_IOV_MultipleVFCreation_withMTU/test_SR_IOV_MultipleVFCreation_withMTU.py
Labels: enhancement

#20 Cleanup utils
  sriov/common/.utils.py.swp
  sriov/common/utils.py
  sriov/tests/SR_IOV_MultipleVFCreation_withMTU/test_SR_IOV_MultipleVFCreation_withMTU.py
  sriov/tests/common/test_utils.py
Labels: documentation, enhancement

#21 Cleanup exec and config in common
  sriov/.gitignore
  sriov/common/.utils.py.swp
  sriov/common/config.py
  sriov/common/exec.py
Labels: documentation

#31 SR-IOV.TrustMode: ignore an error when trying to change mac address in trust mode off
  sriov/tests/SR_IOV_TrustMode/README.md
  sriov/tests/SR_IOV_TrustMode/test_SR_IOV_TrustMode.py
Labels: bug

#25 Test cleanup
  sriov/tests/SR_IOV_InterVF/test_SR_IOV_InterVF.py
  sriov/tests/SR_IOV_InterVF_DPDK/test_SR_IOV_InterVF_DPDK.py
  sriov/tests/SR_IOV_MTU/test_SR_IOV_MTU.py
  sriov/tests/SR_IOV_MultipleVFCreation_withMTU/test_SR_IOV_MultipleVFCreation_withMTU.py
  sriov/tests/SR_IOV_Permutation/test_SR_IOV_Permutation.py
  sriov/tests/SR_IOV_Permutation_DPDK/test_SR_IOV_Permutation_DPDK.py
  sriov/tests/SR_IOV_QinQ/test_SR_IOV_QinQ.py
  sriov/tests/SR_IOV_Spoof_Mac/test_SR_IOV_Spoof_Mac.py
  sriov/tests/SR_IOV_TrustMode/test_SR_IOV_TrustMode.py
  sriov/tests/SR_IOV_macAddress/test_SR_IOV_macAddress.py
  sriov/tests/SR_IOV_macAddress_DPDK/test_SR_IOV_macAddress_DPDK.py
  sriov/tests/common/test_utils.py
Labels: documentation

#26 Kernel hotfix
  sriov/tests/conftest.py
Labels: bug, enhancement

#28 Fix SR_IOV_InterVF_DPDK timing issues in RHEL8.6
  sriov/tests/SR_IOV_InterVF_DPDK/test_SR_IOV_InterVF_DPDK.py
Labels: bug

#39 Hotfix for vf creation checks
  sriov/common/utils.py
Labels: bug

#38 Adding a draft contribution guide
  CONTRIBUTING.md
Labels: documentation

#43 Refactor tests sr iov inter vf
  sriov/common/utils.py
  sriov/tests/SR_IOV_InterVF/test_SR_IOV_InterVF.py
Labels: enhancement

#44 Refactor tests sr iov inter vf dpdk
  sriov/tests/SR_IOV_InterVF_DPDK/test_SR_IOV_InterVF_DPDK.py
Labels: enhancement

#51 Refactor remaining tests
  sriov/tests/SR_IOV_MTU/test_SR_IOV_MTU.py
  sriov/tests/SR_IOV_MultipleVFCreation_withMTU/test_SR_IOV_MultipleVFCreation_withMTU.py
  sriov/tests/SR_IOV_Permutation/test_SR_IOV_Permutation.py
  sriov/tests/SR_IOV_Permutation_DPDK/test_SR_IOV_Permutation_DPDK.py
  sriov/tests/SR_IOV_QinQ/test_SR_IOV_QinQ.py
  sriov/tests/SR_IOV_Spoof_Mac/test_SR_IOV_Spoof_Mac.py
  sriov/tests/SR_IOV_TrustMode/test_SR_IOV_TrustMode.py
  sriov/tests/SR_IOV_macAddress/test_SR_IOV_macAddress.py
  sriov/tests/SR_IOV_macAddress_DPDK/test_SR_IOV_macAddress_DPDK.py
Labels: enhancement
